// Static peak and hub data for the map.
// Elevations, coordinates, route stats and the difficulty / exposure /
// rockfall / route-finding ratings are independently verified facts.
// Hub assignments and the peak notes are editorial.
const CLASS_ORDER = ["Class 1", "Class 2", "Difficult Class 2", "Easy Class 3", "Class 3", "Class 4"];
const RISK_ORDER = ["Low", "Moderate", "Considerable", "High", "Extreme"];
const HUBS = [
 {
  "id": "estes-park",
  "short": "Estes Park",
  "name": "Estes Park",
  "lat": 40.3772,
  "lon": -105.5217,
  "blurb": "Rocky Mountain National Park's front door. Longs is the only 14er here and it's worth its own trip. Book a campsite well ahead.",
  "camping": "Longs Peak CG (first-come, tiny) + Moraine Park CG (reserve)",
  "drive": "~1.5 hr from Denver"
 },
 {
  "id": "georgetown",
  "short": "Georgetown",
  "name": "Georgetown / Idaho Springs",
  "lat": 39.7061,
  "lon": -105.6972,
  "blurb": "I-70 corridor. Closest 14ers to Denver, so trailheads are crowded and parking rules apply. Best as a first or last stop.",
  "camping": "Guanella Pass CG + Clear Creek dispersed",
  "drive": "~1 hr from Denver"
 },
 {
  "id": "colorado-springs",
  "short": "Colo. Springs",
  "name": "Colorado Springs",
  "lat": 38.8339,
  "lon": -104.8214,
  "blurb": "City base for Pikes Peak, which stands alone east of the range. A road and a cog railway reach the summit, which sets the tone.",
  "camping": "Mueller State Park + Pike NF dispersed",
  "drive": "~1.25 hr from Denver"
 },
 {
  "id": "alma",
  "short": "Alma",
  "name": "Alma / Fairplay",
  "lat": 39.2822,
  "lon": -106.0653,
  "blurb": "South Park base for the Mosquito Range. Shortest-effort summits in the state \u2014 good for a half day or a weather-shortened morning.",
  "camping": "Kite Lake CG (fee, fills early) + Weston Pass dispersed",
  "drive": "~1.5 hr from Denver"
 },
 {
  "id": "leadville",
  "short": "Leadville",
  "name": "Leadville",
  "lat": 39.2508,
  "lon": -106.2925,
  "blurb": "Highest incorporated town in the US (10,152 ft). Motels, groceries, and brewpubs, with dispersed camping up Halfmoon Rd. The best all-round base.",
  "camping": "Halfmoon Creek dispersed + Elbert Creek CG",
  "drive": "~2 hr from Denver"
 },
 {
  "id": "buena-vista",
  "short": "Buena Vista",
  "name": "Buena Vista / Salida",
  "lat": 38.8422,
  "lon": -106.1311,
  "blurb": "Warm valley towns on the Arkansas River. Softer weather than Leadville, hot springs nearby, and the Collegiate trailheads are 20-40 min out.",
  "camping": "Collegiate Peaks CG + dispersed on Cottonwood Pass",
  "drive": "~2.5 hr from Denver"
 },
 {
  "id": "aspen",
  "short": "Aspen",
  "name": "Aspen",
  "lat": 39.1911,
  "lon": -106.8175,
  "blurb": "Gateway to the Elk Range \u2014 the most beautiful and most lethal 14ers in Colorado. Expensive; camp instead. Maroon Bells needs a reservation.",
  "camping": "Silver Bar/Bell CGs (reserve) + Lincoln Creek dispersed",
  "drive": "~4 hr from Denver"
 },
 {
  "id": "westcliffe",
  "short": "Westcliffe",
  "name": "Westcliffe / Crestone",
  "lat": 38.1347,
  "lon": -105.4675,
  "blurb": "Under the abrupt east wall of the Sangre de Cristos. Dark-sky town, little traffic. South Colony Lakes road is rough past the 2WD lot.",
  "camping": "South Colony Lakes dispersed (4WD) + Alvarado CG",
  "drive": "~3.5 hr from Denver"
 },
 {
  "id": "fort-garland",
  "short": "Fort Garland",
  "name": "Fort Garland / Blanca",
  "lat": 37.4258,
  "lon": -105.4319,
  "blurb": "San Luis Valley base for the Blanca massif and Lindsey. Lake Como Road is one of the roughest 4WD roads in Colorado \u2014 most people walk it.",
  "camping": "Lake Como Rd dispersed (walk-in) + Zapata Falls CG",
  "drive": "~4 hr from Denver"
 },
 {
  "id": "creede",
  "short": "Creede",
  "name": "Creede",
  "lat": 37.8492,
  "lon": -106.9264,
  "blurb": "Old mining town at the head of the Rio Grande. Quiet approach to San Luis Peak, the most isolated 14er in the state.",
  "camping": "Rio Grande NF dispersed (Stewart Creek)",
  "drive": "~4.5 hr from Denver"
 },
 {
  "id": "lake-city",
  "short": "Lake City",
  "name": "Lake City",
  "lat": 38.0302,
  "lon": -107.3159,
  "blurb": "Remote, quiet, and surrounded by the best of the San Juans. Alpine Loop 4WD roads reach several trailheads. Stock up before you arrive.",
  "camping": "Alpine Loop dispersed (Grizzly Gulch, Nellie Creek)",
  "drive": "~5 hr from Denver"
 },
 {
  "id": "ouray",
  "short": "Ouray",
  "name": "Ouray",
  "lat": 38.0228,
  "lon": -107.6714,
  "blurb": "'Switzerland of America' in a box canyon. Hot springs to soak in after Sneffels. Yankee Boy Basin road needs clearance near the top.",
  "camping": "Yankee Boy Basin dispersed + Amphitheater CG",
  "drive": "~6 hr from Denver"
 },
 {
  "id": "telluride",
  "short": "Telluride",
  "name": "Telluride",
  "lat": 37.9375,
  "lon": -107.8123,
  "blurb": "Box-canyon ski town under the Wilson group, the most striking skyline in Colorado. Over Ophir or Imogene Pass from Ouray if you have the clearance.",
  "camping": "Sunshine CG + Alta Lakes dispersed",
  "drive": "~6.5 hr from Denver"
 },
 {
  "id": "durango",
  "short": "Durango",
  "name": "Durango / Silverton",
  "lat": 37.2753,
  "lon": -107.8801,
  "blurb": "Access to Chicago Basin, which is a train ride and a backpack rather than a drive. Reserve the Durango & Silverton narrow gauge well ahead.",
  "camping": "Chicago Basin backcountry (2 nights) + Purgatory Flats",
  "drive": "~6.5 hr from Denver"
 }
];
const PEAKS = [
 {
  "name": "Mount Elbert",
  "id": 10001,
  "hub": "leadville",
  "featured": true,
  "note": "The state highpoint on a good trail the whole way. Long but never technical — the single best warm-up in Colorado.",
  "lat": 39.11774,
  "lon": -106.44537,
  "elev": 14438,
  "range": "Sawatch Range",
  "rank": 1,
  "route": "Mt. Elbert - Northeast Ridge",
  "cls": "Class 1",
  "dist": "9.75 mi",
  "gain": "4,500'",
  "exposure": "Low",
  "rockfall": "Low",
  "routefinding": "Low",
  "commitment": "Low"
 },
 {
  "name": "Mount Massive",
  "id": 10002,
  "hub": "leadville",
  "featured": true,
  "note": "Shares the Colorado Trail approach with Elbert. Sprawling summit ridge with five points over 14,000 ft; the distance is the crux, not the terrain.",
  "lat": 39.18753,
  "lon": -106.47559,
  "elev": 14427,
  "range": "Sawatch Range",
  "rank": 2,
  "route": "Mt. Massive - East Slopes",
  "cls": "Class 2",
  "dist": "13.75 mi",
  "gain": "4,500'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Moderate",
  "commitment": "Moderate"
 },
 {
  "name": "Mount Harvard",
  "id": 10003,
  "hub": "buena-vista",
  "featured": false,
  "note": "Long, gorgeous walk up Horn Fork Basin to the third-highest point in the state. A few easy moves right at the summit block.",
  "lat": 38.92442,
  "lon": -106.32079,
  "elev": 14424,
  "range": "Sawatch Range",
  "rank": 3,
  "route": "Mt. Harvard - South Slopes",
  "cls": "Class 2",
  "dist": "13.75 mi",
  "gain": "4,600'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Moderate",
  "commitment": "Moderate"
 },
 {
  "name": "Blanca Peak",
  "id": 10004,
  "hub": "fort-garland",
  "featured": false,
  "note": "Big, remote, and guarded by Lake Como Road — one of the roughest 4WD roads in the state. Most people walk several miles just to reach the trailhead.",
  "lat": 37.57753,
  "lon": -105.48569,
  "elev": 14350,
  "range": "Sangre de Cristo",
  "rank": 4,
  "route": "Blanca Peak - Northwest Ridge",
  "cls": "Difficult Class 2",
  "dist": "17 mi",
  "gain": "6,500'",
  "exposure": "Considerable",
  "rockfall": "Considerable",
  "routefinding": "Moderate",
  "commitment": "Considerable"
 },
 {
  "name": "La Plata Peak",
  "id": 10005,
  "hub": "leadville",
  "featured": false,
  "note": "Steep, sustained, and steadily beautiful. A short talus rib near 13,000 ft gets your hands out but stays easy.",
  "lat": 39.02949,
  "lon": -106.473,
  "elev": 14344,
  "range": "Sawatch Range",
  "rank": 5,
  "route": "La Plata Peak - Northwest Ridge",
  "cls": "Class 2",
  "dist": "9.25 mi",
  "gain": "4,400'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Moderate"
 },
 {
  "name": "Uncompahgre Peak",
  "id": 10006,
  "hub": "lake-city",
  "featured": false,
  "note": "A tilted mesa with a 700-ft north wall — highest of the San Juans. Nellie Creek road to the trailhead wants 4WD.",
  "lat": 38.07168,
  "lon": -107.46211,
  "elev": 14318,
  "range": "San Juan Mountains",
  "rank": 6,
  "route": "Uncompahgre Peak - South Ridge",
  "cls": "Class 2",
  "dist": "7.5 mi",
  "gain": "3,000'",
  "exposure": "Moderate",
  "rockfall": "Considerable",
  "routefinding": "Moderate",
  "commitment": "Moderate"
 },
 {
  "name": "Crestone Peak",
  "id": 10007,
  "hub": "westcliffe",
  "featured": false,
  "note": "The red gully is long and committing, and the traverse to the Needle is one of the great hard classics in the state.",
  "lat": 37.96688,
  "lon": -105.58538,
  "elev": 14299,
  "range": "Sangre de Cristo",
  "rank": 7,
  "route": "Crestone Peak - South Face",
  "cls": "Class 3",
  "dist": "14 mi",
  "gain": "5,700'",
  "exposure": "High",
  "rockfall": "Considerable",
  "routefinding": "Considerable",
  "commitment": "Considerable"
 },
 {
  "name": "Mount Lincoln",
  "id": 10008,
  "hub": "alma",
  "featured": false,
  "note": "Third stop on the DeCaLiBron loop and the highest of the four.",
  "lat": 39.35145,
  "lon": -106.11156,
  "elev": 14293,
  "range": "Mosquito Range",
  "rank": 8,
  "route": "Mt. Lincoln - West Ridge",
  "cls": "Class 2",
  "dist": "6 mi",
  "gain": "2,600'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Low"
 },
 {
  "name": "Grays Peak",
  "id": 10009,
  "hub": "georgetown",
  "featured": false,
  "note": "Wide, well-graded trail and the highest point on the Continental Divide. Pair with Torreys — the connecting saddle is 15 minutes of work.",
  "lat": 39.63383,
  "lon": -105.81763,
  "elev": 14275,
  "range": "Front Range",
  "rank": 9,
  "route": "Grays Peak - North Slopes",
  "cls": "Class 1",
  "dist": "7.5 mi",
  "gain": "3,000'",
  "exposure": "Low",
  "rockfall": "Low",
  "routefinding": "Low",
  "commitment": "Low"
 },
 {
  "name": "Castle Peak",
  "id": 10012,
  "hub": "aspen",
  "featured": false,
  "note": "The friendliest of the Elks by a wide margin, and often a snow climb into July. Conundrum Peak is a 20-minute add-on from the saddle.",
  "lat": 39.00974,
  "lon": -106.86135,
  "elev": 14274,
  "range": "Elk Mountains",
  "rank": 10,
  "route": "Castle Peak - Northeast Ridge",
  "cls": "Difficult Class 2",
  "dist": "13.5 mi",
  "gain": "4,600'",
  "exposure": "Considerable",
  "rockfall": "Considerable",
  "routefinding": "Considerable",
  "commitment": "Considerable"
 },
 {
  "name": "Quandary Peak",
  "id": 10013,
  "hub": "alma",
  "featured": true,
  "note": "The most efficient 14er in the state and the busiest. Trailhead parking is reservation/shuttle-only in summer — check before you drive up.",
  "lat": 39.39727,
  "lon": -106.10643,
  "elev": 14272,
  "range": "Tenmile Range",
  "rank": 11,
  "route": "Quandary Peak - East Ridge",
  "cls": "Class 1",
  "dist": "6.75 mi",
  "gain": "3,450'",
  "exposure": "Low",
  "rockfall": "Low",
  "routefinding": "Low",
  "commitment": "Low"
 },
 {
  "name": "Torreys Peak",
  "id": 10011,
  "hub": "georgetown",
  "featured": false,
  "note": "Almost always climbed with Grays. The Kelso Ridge alternative is a superb Class 3 line if you want a step up on the same approach.",
  "lat": 39.64276,
  "lon": -105.82123,
  "elev": 14272,
  "range": "Front Range",
  "rank": 12,
  "route": "Torreys Peak - South Slopes",
  "cls": "Class 1",
  "dist": "7.75 mi",
  "gain": "3,000'",
  "exposure": "Low",
  "rockfall": "Low",
  "routefinding": "Low",
  "commitment": "Low"
 },
 {
  "name": "Mount Antero",
  "id": 10010,
  "hub": "buena-vista",
  "featured": false,
  "note": "A 4WD road runs to well above 13,000 ft, so this is mostly a road walk unless you drive it. Famous for gem hunting.",
  "lat": 38.67414,
  "lon": -106.24621,
  "elev": 14271,
  "range": "Sawatch Range",
  "rank": 13,
  "route": "Mt. Antero - West Slopes",
  "cls": "Class 2",
  "dist": "15.5 mi",
  "gain": "5,200'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Moderate"
 },
 {
  "name": "Mount Blue Sky",
  "id": 10014,
  "hub": "georgetown",
  "featured": false,
  "note": "Formerly Mount Evans. A paved road reaches the summit, so the hike is optional — the Sawtooth from Bierstadt is the interesting way up.",
  "lat": 39.58835,
  "lon": -105.64363,
  "elev": 14268,
  "range": "Front Range",
  "rank": 14,
  "route": "Mt. Blue Sky - West Ridge from Summit Lake",
  "cls": "Class 2",
  "dist": "5.5 mi",
  "gain": "2,000'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Moderate",
  "commitment": "Moderate"
 },
 {
  "name": "Longs Peak",
  "id": 10015,
  "hub": "estes-park",
  "featured": true,
  "note": "The Keyhole is the most famous route in Colorado and the most underestimated. Ledges, Trough, Narrows, Homestretch — all serious once wet or icy. Alpine start around 2am, and be off the summit by late morning.",
  "lat": 40.25502,
  "lon": -105.61507,
  "elev": 14259,
  "range": "Front Range",
  "rank": 15,
  "route": "Longs Peak - Keyhole Route",
  "cls": "Class 3",
  "dist": "14.5 mi",
  "gain": "5,100'",
  "exposure": "High",
  "rockfall": "Considerable",
  "routefinding": "Considerable",
  "commitment": "High"
 },
 {
  "name": "Mount Wilson",
  "id": 10016,
  "hub": "telluride",
  "featured": false,
  "note": "Serious, loose, and committing, with a genuinely hard summit block. Often paired with El Diente via a long traverse.",
  "lat": 37.83912,
  "lon": -107.99164,
  "elev": 14256,
  "range": "San Juan Mountains",
  "rank": 16,
  "route": "Mt. Wilson - Southwest Slopes",
  "cls": "Class 3",
  "dist": "12.5 mi",
  "gain": "4,400'",
  "exposure": "High",
  "rockfall": "Considerable",
  "routefinding": "Considerable",
  "commitment": "Considerable"
 },
 {
  "name": "Mount Cameron",
  "id": 10063,
  "hub": "alma",
  "featured": false,
  "note": "Unranked bump between Democrat and Lincoln. You walk over it either way.",
  "lat": 39.34627,
  "lon": -106.11902,
  "elev": 14248,
  "range": "Mosquito Range",
  "rank": 99,
  "route": "Mt. Cameron - West Ridge",
  "cls": "Class 2",
  "dist": "4.75 mi",
  "gain": "2,250'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Low"
 },
 {
  "name": "Mount Shavano",
  "id": 10017,
  "hub": "buena-vista",
  "featured": false,
  "note": "Home of the Angel of Shavano, a snow couloir visible from the valley all spring. Usually paired with Tabeguache.",
  "lat": 38.61909,
  "lon": -106.23929,
  "elev": 14230,
  "range": "Sawatch Range",
  "rank": 17,
  "route": "Mt. Shavano - East Slopes",
  "cls": "Class 2",
  "dist": "10 mi",
  "gain": "4,500'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Moderate"
 },
 {
  "name": "Mount Belford",
  "id": 10018,
  "hub": "leadville",
  "featured": false,
  "note": "Relentless switchbacks out of Missouri Gulch. Bag Mount Oxford on the same day via the connecting ridge for a cheap second summit.",
  "lat": 38.9607,
  "lon": -106.36064,
  "elev": 14202,
  "range": "Sawatch Range",
  "rank": 18,
  "route": "Mt. Belford - Northwest Ridge",
  "cls": "Class 2",
  "dist": "8 mi",
  "gain": "4,500'",
  "exposure": "Low",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Moderate"
 },
 {
  "name": "Mount Princeton",
  "id": 10020,
  "hub": "buena-vista",
  "featured": false,
  "note": "Stats assume the rough road to the radio towers; from the bottom it's far longer. Loose sidehill traverse, and a hot springs soak waiting below.",
  "lat": 38.74919,
  "lon": -106.24244,
  "elev": 14200,
  "range": "Sawatch Range",
  "rank": 19,
  "route": "Mt. Princeton - East Slopes",
  "cls": "Class 2",
  "dist": "6.5 mi",
  "gain": "3,200'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Moderate",
  "commitment": "Moderate"
 },
 {
  "name": "Mount Yale",
  "id": 10021,
  "hub": "buena-vista",
  "featured": false,
  "note": "Straightforward Collegiate with an unusually good summit view down the Arkansas Valley. Easy access off Cottonwood Pass Rd.",
  "lat": 38.84419,
  "lon": -106.31381,
  "elev": 14200,
  "range": "Sawatch Range",
  "rank": 20,
  "route": "Mt. Yale - Southwest Slopes",
  "cls": "Class 2",
  "dist": "9.5 mi",
  "gain": "4,300'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Moderate"
 },
 {
  "name": "Crestone Needle",
  "id": 10019,
  "hub": "westcliffe",
  "featured": false,
  "note": "Twin gullies on superb, grippy conglomerate — some of the best rock in the state. The classic error is crossing into the wrong gully too low.",
  "lat": 37.9647,
  "lon": -105.57674,
  "elev": 14196,
  "range": "Sangre de Cristo",
  "rank": 21,
  "route": "Crestone Needle - South Face",
  "cls": "Class 4",
  "dist": "12 mi",
  "gain": "4,400'",
  "exposure": "High",
  "rockfall": "Considerable",
  "routefinding": "High",
  "commitment": "Considerable"
 },
 {
  "name": "Mount Bross",
  "id": 10022,
  "hub": "alma",
  "featured": false,
  "note": "Fourth on the DeCaLiBron. The summit itself has been closed by private claims — check current access before counting on it.",
  "lat": 39.33545,
  "lon": -106.10773,
  "elev": 14178,
  "range": "Mosquito Range",
  "rank": 22,
  "route": "Mt. Bross - West Slopes",
  "cls": "Class 2",
  "dist": "3.25 mi",
  "gain": "2,250'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Low"
 },
 {
  "name": "El Diente Peak",
  "id": 10064,
  "hub": "telluride",
  "featured": false,
  "note": "Unranked but harder than most ranked peaks — loose rock and real routefinding. The traverse to Mount Wilson is a classic and a commitment.",
  "lat": 37.83922,
  "lon": -108.00534,
  "elev": 14175,
  "range": "San Juan Mountains",
  "rank": 99,
  "route": "El Diente Peak - South Slopes",
  "cls": "Class 3",
  "dist": "12 mi",
  "gain": "4,400'",
  "exposure": "Considerable",
  "rockfall": "Considerable",
  "routefinding": "High",
  "commitment": "Considerable"
 },
 {
  "name": "Kit Carson Peak",
  "id": 10023,
  "hub": "westcliffe",
  "featured": false,
  "note": "Reached over Challenger Point, so you get two summits. The Avenue ledge is obvious in daylight and treacherous to improvise in the dark.",
  "lat": 37.97965,
  "lon": -105.60255,
  "elev": 14167,
  "range": "Sangre de Cristo",
  "rank": 23,
  "route": "Kit Carson Peak - Via Challenger Point",
  "cls": "Easy Class 3",
  "dist": "15 mi",
  "gain": "6,250'",
  "exposure": "Considerable",
  "rockfall": "Considerable",
  "routefinding": "Considerable",
  "commitment": "Considerable"
 },
 {
  "name": "Maroon Peak",
  "id": 10024,
  "hub": "aspen",
  "featured": false,
  "note": "South Maroon. Long, loose, and complex, with a route that punishes anyone who improvises — the Bells have killed a lot of experienced people.",
  "lat": 39.07084,
  "lon": -106.989,
  "elev": 14163,
  "range": "Elk Mountains",
  "rank": 24,
  "route": "Maroon Peak - South Ridge",
  "cls": "Class 3",
  "dist": "12 mi",
  "gain": "4,800'",
  "exposure": "High",
  "rockfall": "High",
  "routefinding": "Extreme",
  "commitment": "Extreme"
 },
 {
  "name": "Mount Oxford",
  "id": 10026,
  "hub": "leadville",
  "featured": false,
  "note": "A two-mile round trip from Belford's summit along an easy ridge. Rarely climbed on its own, and there's no reason to.",
  "lat": 38.96482,
  "lon": -106.33883,
  "elev": 14158,
  "range": "Sawatch Range",
  "rank": 25,
  "route": "Mt. Oxford - Via Mt. Belford",
  "cls": "Class 2",
  "dist": "11 mi",
  "gain": "5,900'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Considerable"
 },
 {
  "name": "Tabeguache Peak",
  "id": 10025,
  "hub": "buena-vista",
  "featured": false,
  "note": "Reached over Shavano's summit, which means reclimbing Shavano on the way out.",
  "lat": 38.62549,
  "lon": -106.25082,
  "elev": 14158,
  "range": "Sawatch Range",
  "rank": 26,
  "route": "Tabeguache Peak - Via Mt. Shavano",
  "cls": "Class 2",
  "dist": "12 mi",
  "gain": "5,600'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Moderate",
  "commitment": "Considerable"
 },
 {
  "name": "Mount Sneffels",
  "id": 10027,
  "hub": "ouray",
  "featured": false,
  "note": "Steep loose gully to a notch, then a short crux. Rockfall from parties above is the real hazard — helmet, and don't stack up in the gully.",
  "lat": 38.00382,
  "lon": -107.79235,
  "elev": 14155,
  "range": "San Juan Mountains",
  "rank": 27,
  "route": "Mt. Sneffels - South Slopes",
  "cls": "Easy Class 3",
  "dist": "6 mi",
  "gain": "2,900'",
  "exposure": "Considerable",
  "rockfall": "Considerable",
  "routefinding": "Moderate",
  "commitment": "Moderate"
 },
 {
  "name": "Mount Democrat",
  "id": 10028,
  "hub": "alma",
  "featured": false,
  "note": "Anchor of the DeCaLiBron loop (Democrat–Cameron–Lincoln–Bross): four summits in a morning. The loop crosses private mining claims and has closed before — verify access first.",
  "lat": 39.33958,
  "lon": -106.14005,
  "elev": 14154,
  "range": "Mosquito Range",
  "rank": 28,
  "route": "Mt. Democrat - East Slope",
  "cls": "Class 2",
  "dist": "4 mi",
  "gain": "2,150'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Low"
 },
 {
  "name": "Capitol Peak",
  "id": 10029,
  "hub": "aspen",
  "featured": false,
  "note": "The Knife Edge and the hardest standard route in Colorado. A long backpack in, sustained exposure, and a well-earned reputation for fatalities — almost all from people shortcutting the descent.",
  "lat": 39.15026,
  "lon": -107.08294,
  "elev": 14138,
  "range": "Elk Mountains",
  "rank": 29,
  "route": "Capitol Peak - Northeast Ridge",
  "cls": "Class 4",
  "dist": "17 mi",
  "gain": "5,300'",
  "exposure": "High",
  "rockfall": "High",
  "routefinding": "High",
  "commitment": "Extreme"
 },
 {
  "name": "Pikes Peak",
  "id": 10030,
  "hub": "colorado-springs",
  "featured": false,
  "note": "Stands alone east of the range with huge prominence and a big view. Also has a road, a cog railway and a doughnut shop on top.",
  "lat": 38.84034,
  "lon": -105.04375,
  "elev": 14109,
  "range": "Front Range",
  "rank": 30,
  "route": "Pikes Peak - East Slopes",
  "cls": "Class 1",
  "dist": "24 mi",
  "gain": "7,600'",
  "exposure": "Low",
  "rockfall": "Low",
  "routefinding": "Low",
  "commitment": "Moderate"
 },
 {
  "name": "Snowmass Mountain",
  "id": 10031,
  "hub": "aspen",
  "featured": false,
  "note": "Backpack to Snowmass Lake, climb the peak at dawn. One of the great camps in Colorado. The summit ridge is looser than it looks.",
  "lat": 39.11875,
  "lon": -107.06644,
  "elev": 14105,
  "range": "Elk Mountains",
  "rank": 31,
  "route": "Snowmass Mountain - East Slopes",
  "cls": "Class 3",
  "dist": "22 mi",
  "gain": "5,800'",
  "exposure": "High",
  "rockfall": "Considerable",
  "routefinding": "Considerable",
  "commitment": "High"
 },
 {
  "name": "Windom Peak",
  "id": 10033,
  "hub": "durango",
  "featured": false,
  "note": "Chicago Basin: ride the narrow gauge, backpack in, and climb three 14ers over a couple of days. Windom is the most straightforward of them.",
  "lat": 37.62123,
  "lon": -107.59191,
  "elev": 14089,
  "range": "San Juan Mountains",
  "rank": 32,
  "route": "Windom Peak - West Ridge",
  "cls": "Difficult Class 2",
  "dist": "6 mi",
  "gain": "3,000'",
  "exposure": "Considerable",
  "rockfall": "Considerable",
  "routefinding": "Moderate",
  "commitment": "Moderate"
 },
 {
  "name": "Mount Eolus",
  "id": 10032,
  "hub": "durango",
  "featured": false,
  "note": "The Catwalk is a narrow, airy rib leading to good scrambling above.",
  "lat": 37.62195,
  "lon": -107.62272,
  "elev": 14087,
  "range": "San Juan Mountains",
  "rank": 33,
  "route": "Mt. Eolus - Northeast Ridge",
  "cls": "Class 3",
  "dist": "6 mi",
  "gain": "3,100'",
  "exposure": "High",
  "rockfall": "Considerable",
  "routefinding": "Considerable",
  "commitment": "Considerable"
 },
 {
  "name": "Challenger Point",
  "id": 10034,
  "hub": "westcliffe",
  "featured": false,
  "note": "The steep, loose staircase you climb on the way to Kit Carson. Named for the shuttle crew.",
  "lat": 37.98033,
  "lon": -105.60659,
  "elev": 14086,
  "range": "Sangre de Cristo",
  "rank": 99,
  "route": "Challenger Point - North Slope",
  "cls": "Difficult Class 2",
  "dist": "13.5 mi",
  "gain": "5,400'",
  "exposure": "Considerable",
  "rockfall": "Considerable",
  "routefinding": "Considerable",
  "commitment": "Moderate"
 },
 {
  "name": "Mount Columbia",
  "id": 10035,
  "hub": "buena-vista",
  "featured": false,
  "note": "Usually done as a traverse from Harvard. The direct west slopes are a notorious loose-scree grind that people regret.",
  "lat": 38.90402,
  "lon": -106.29752,
  "elev": 14075,
  "range": "Sawatch Range",
  "rank": 34,
  "route": "Mt. Columbia - West Slopes",
  "cls": "Class 2",
  "dist": "12 mi",
  "gain": "4,250'",
  "exposure": "Moderate",
  "rockfall": "Considerable",
  "routefinding": "Moderate",
  "commitment": "Moderate"
 },
 {
  "name": "Missouri Mountain",
  "id": 10036,
  "hub": "leadville",
  "featured": false,
  "note": "Same Missouri Gulch trailhead as Belford but a far better summit — a narrow ridge with a short, airy notch near the top.",
  "lat": 38.94757,
  "lon": -106.37844,
  "elev": 14071,
  "range": "Sawatch Range",
  "rank": 35,
  "route": "Missouri Mountain - Northwest Ridge",
  "cls": "Class 2",
  "dist": "10.5 mi",
  "gain": "4,500'",
  "exposure": "Considerable",
  "rockfall": "Considerable",
  "routefinding": "Low",
  "commitment": "Moderate"
 },
 {
  "name": "Humboldt Peak",
  "id": 10037,
  "hub": "westcliffe",
  "featured": false,
  "note": "The safe seat in the house: an easy walk-up with a front-row view of the Crestones. Ideal recon day before committing to anything harder.",
  "lat": 37.97618,
  "lon": -105.55534,
  "elev": 14068,
  "range": "Sangre de Cristo",
  "rank": 36,
  "route": "Humboldt Peak - West Ridge",
  "cls": "Class 2",
  "dist": "11 mi",
  "gain": "4,200'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Moderate",
  "commitment": "Low"
 },
 {
  "name": "Mount Bierstadt",
  "id": 10038,
  "hub": "georgetown",
  "featured": false,
  "note": "Willow bushwhack at the start, then an easy walk. The Sawtooth traverse to Blue Sky is a serious upgrade — don't wander onto it casually.",
  "lat": 39.58256,
  "lon": -105.66886,
  "elev": 14066,
  "range": "Front Range",
  "rank": 37,
  "route": "Mt. Bierstadt - West Slopes",
  "cls": "Class 2",
  "dist": "7.25 mi",
  "gain": "2,850'",
  "exposure": "Low",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Low"
 },
 {
  "name": "Sunlight Peak",
  "id": 10039,
  "hub": "durango",
  "featured": false,
  "note": "The summit block is a committing move over a gap with the whole basin below — many people reach the top and decline the last few feet.",
  "lat": 37.62742,
  "lon": -107.59573,
  "elev": 14061,
  "range": "San Juan Mountains",
  "rank": 38,
  "route": "Sunlight Peak - South Face",
  "cls": "Class 4",
  "dist": "6 mi",
  "gain": "3,000'",
  "exposure": "Extreme",
  "rockfall": "Considerable",
  "routefinding": "Considerable",
  "commitment": "Considerable"
 },
 {
  "name": "Handies Peak",
  "id": 10040,
  "hub": "lake-city",
  "featured": false,
  "note": "Easiest San Juan summit, off the Alpine Loop. Wildflowers in American Basin in July are the best in Colorado. Full stop.",
  "lat": 37.91297,
  "lon": -107.50439,
  "elev": 14058,
  "range": "San Juan Mountains",
  "rank": 39,
  "route": "Handies Peak - Southwest Slopes",
  "cls": "Class 1",
  "dist": "5.75 mi",
  "gain": "2,500'",
  "exposure": "Moderate",
  "rockfall": "Low",
  "routefinding": "Low",
  "commitment": "Low"
 },
 {
  "name": "Ellingwood Point",
  "id": 10042,
  "hub": "fort-garland",
  "featured": false,
  "note": "Blanca's neighbor, usually climbed the same day from Lake Como.",
  "lat": 37.58257,
  "lon": -105.49248,
  "elev": 14057,
  "range": "Sangre de Cristo",
  "rank": 40,
  "route": "Ellingwood Point - South Face",
  "cls": "Difficult Class 2",
  "dist": "17 mi",
  "gain": "6,200'",
  "exposure": "Considerable",
  "rockfall": "Considerable",
  "routefinding": "Considerable",
  "commitment": "Considerable"
 },
 {
  "name": "Mount Lindsey",
  "id": 10043,
  "hub": "fort-garland",
  "featured": false,
  "note": "Quieter Sangre summit with a fun gully. Access crosses private land and has been closed before — check first.",
  "lat": 37.58389,
  "lon": -105.4449,
  "elev": 14055,
  "range": "Sangre de Cristo",
  "rank": 41,
  "route": "Mt. Lindsey - Northwest Gully",
  "cls": "Easy Class 3",
  "dist": "8.25 mi",
  "gain": "3,500'",
  "exposure": "Considerable",
  "rockfall": "Considerable",
  "routefinding": "Considerable",
  "commitment": "Moderate"
 },
 {
  "name": "Culebra Peak",
  "id": 10041,
  "hub": "fort-garland",
  "featured": false,
  "note": "Entirely on private ranch land: paid permit, limited days, reserved ahead. The opposite of spontaneous, but a friendly walk once you're on it.",
  "lat": 37.12233,
  "lon": -105.18573,
  "elev": 14053,
  "range": "Sangre de Cristo",
  "rank": 42,
  "route": "Culebra Peak - Northwest Ridge",
  "cls": "Class 2",
  "dist": "5 mi",
  "gain": "2,750'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Moderate",
  "commitment": "Moderate"
 },
 {
  "name": "Mount Sherman",
  "id": 10045,
  "hub": "alma",
  "featured": false,
  "note": "The shortest 14er day in the state, through photogenic mine ruins. Very exposed ridge in wind, and the structures are unsafe to enter.",
  "lat": 39.22509,
  "lon": -106.17009,
  "elev": 14043,
  "range": "Mosquito Range",
  "rank": 43,
  "route": "Mt. Sherman - Southwest Ridge",
  "cls": "Class 1",
  "dist": "5.25 mi",
  "gain": "2,100'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Low"
 },
 {
  "name": "North Eolus",
  "id": 10066,
  "hub": "durango",
  "featured": false,
  "note": "Unranked, twenty minutes from Eolus's saddle, and a fine short scramble.",
  "lat": 37.62519,
  "lon": -107.62117,
  "elev": 14042,
  "range": "San Juan Mountains",
  "rank": 99,
  "route": "North Eolus - South Ridge",
  "cls": "Class 3",
  "dist": "0.2 mi",
  "gain": "250'",
  "exposure": "Considerable",
  "rockfall": "Moderate",
  "routefinding": "Moderate",
  "commitment": "Moderate"
 },
 {
  "name": "Little Bear Peak",
  "id": 10044,
  "hub": "fort-garland",
  "featured": false,
  "note": "The Hourglass is a rockfall funnel with a bad fatality record, and parties above you are the hazard. One of the two or three most dangerous 14ers.",
  "lat": 37.56672,
  "lon": -105.49724,
  "elev": 14041,
  "range": "Sangre de Cristo",
  "rank": 44,
  "route": "Little Bear Peak - West Ridge and Hourglass",
  "cls": "Class 4",
  "dist": "14 mi",
  "gain": "6,200'",
  "exposure": "High",
  "rockfall": "High",
  "routefinding": "High",
  "commitment": "High"
 },
 {
  "name": "Redcloud Peak",
  "id": 10046,
  "hub": "lake-city",
  "featured": false,
  "note": "Long, mellow, and usually combined with Sunshine. Good weather-window pair.",
  "lat": 37.94092,
  "lon": -107.42172,
  "elev": 14037,
  "range": "San Juan Mountains",
  "rank": 45,
  "route": "Redcloud Peak - Northeast Ridge",
  "cls": "Class 2",
  "dist": "9 mi",
  "gain": "3,700'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Low"
 },
 {
  "name": "Conundrum Peak",
  "id": 10065,
  "hub": "aspen",
  "featured": false,
  "note": "Unranked neighbor of Castle, twenty minutes off the saddle. Free summit if you're already there.",
  "lat": 39.01474,
  "lon": -106.86346,
  "elev": 14037,
  "range": "Elk Mountains",
  "rank": 99,
  "route": "Conundrum Peak - South Ridge",
  "cls": "Difficult Class 2",
  "dist": "13.5 mi",
  "gain": "4,400'",
  "exposure": "Considerable",
  "rockfall": "Considerable",
  "routefinding": "Moderate",
  "commitment": "Moderate"
 },
 {
  "name": "Pyramid Peak",
  "id": 10047,
  "hub": "aspen",
  "featured": false,
  "note": "Steep, loose, and unforgiving, with routefinding that punishes guessing. Superb line for climbers who already move well on bad rock — not a first scramble.",
  "lat": 39.07169,
  "lon": -106.95017,
  "elev": 14029,
  "range": "Elk Mountains",
  "rank": 46,
  "route": "Pyramid Peak - Northeast Ridge",
  "cls": "Class 4",
  "dist": "8.25 mi",
  "gain": "4,500'",
  "exposure": "High",
  "rockfall": "High",
  "routefinding": "High",
  "commitment": "High"
 },
 {
  "name": "San Luis Peak",
  "id": 10050,
  "hub": "creede",
  "featured": false,
  "note": "The most isolated 14er in Colorado — a long drive and a gentle, empty walk. Solitude is the whole point.",
  "lat": 37.98678,
  "lon": -106.93127,
  "elev": 14023,
  "range": "San Juan Mountains",
  "rank": 47,
  "route": "San Luis Peak - Northeast Ridge",
  "cls": "Class 1",
  "dist": "13.5 mi",
  "gain": "3,600'",
  "exposure": "Low",
  "rockfall": "Low",
  "routefinding": "Low",
  "commitment": "Low"
 },
 {
  "name": "North Maroon Peak",
  "id": 10067,
  "hub": "aspen",
  "featured": false,
  "note": "The one in the postcard. Steep, loose Class 4 with serious consequences; the traverse to South Maroon is harder still.",
  "lat": 39.07599,
  "lon": -106.98714,
  "elev": 14022,
  "range": "Elk Mountains",
  "rank": 48,
  "route": "North Maroon Peak - Northeast Ridge",
  "cls": "Class 4",
  "dist": "9.25 mi",
  "gain": "4,600'",
  "exposure": "High",
  "rockfall": "High",
  "routefinding": "High",
  "commitment": "High"
 },
 {
  "name": "Wetterhorn Peak",
  "id": 10049,
  "hub": "lake-city",
  "featured": false,
  "note": "The best scramble for its grade in the state — solid rock, obvious line, a genuinely exposed final headwall. A great first Class 3.",
  "lat": 38.06071,
  "lon": -107.51088,
  "elev": 14021,
  "range": "San Juan Mountains",
  "rank": 49,
  "route": "Wetterhorn Peak - Southeast Ridge",
  "cls": "Class 3",
  "dist": "7 mi",
  "gain": "3,300'",
  "exposure": "High",
  "rockfall": "Considerable",
  "routefinding": "Considerable",
  "commitment": "Considerable"
 },
 {
  "name": "Wilson Peak",
  "id": 10048,
  "hub": "telluride",
  "featured": false,
  "note": "The Coors label mountain. Fun, exposed ridge climbing with a memorable false summit, and access here was contested for years — respect the current routing across private land.",
  "lat": 37.86018,
  "lon": -107.98479,
  "elev": 14021,
  "range": "San Juan Mountains",
  "rank": 50,
  "route": "Wilson Peak - Southwest Ridge",
  "cls": "Class 3",
  "dist": "10 mi",
  "gain": "3,900'",
  "exposure": "High",
  "rockfall": "Considerable",
  "routefinding": "Considerable",
  "commitment": "Considerable"
 },
 {
  "name": "Mount of the Holy Cross",
  "id": 10051,
  "hub": "leadville",
  "featured": false,
  "note": "You climb 1,000 ft over Half Moon Pass, descend it, then climb the peak — and repeat in reverse. Notorious for lost hikers on the descent. Do not improvise a shortcut down into the Bowl of Tears.",
  "lat": 39.46683,
  "lon": -106.48169,
  "elev": 14007,
  "range": "Sawatch Range",
  "rank": 51,
  "route": "Mt. of the Holy Cross - North Ridge",
  "cls": "Class 2",
  "dist": "11.25 mi",
  "gain": "5,600'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Moderate",
  "commitment": "Considerable"
 },
 {
  "name": "Huron Peak",
  "id": 10052,
  "hub": "leadville",
  "featured": true,
  "note": "Short, friendly, and the best summit view in the Sawatch: the Three Apostles fill the skyline. Ideal weather-window peak.",
  "lat": 38.94553,
  "lon": -106.43807,
  "elev": 14006,
  "range": "Sawatch Range",
  "rank": 52,
  "route": "Huron Peak - Northwest Slopes",
  "cls": "Class 2",
  "dist": "7 mi",
  "gain": "3,500'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Low"
 },
 {
  "name": "Sunshine Peak",
  "id": 10053,
  "hub": "lake-city",
  "featured": false,
  "note": "A mile and a half past Redcloud along an easy ridge; rarely climbed alone.",
  "lat": 37.92275,
  "lon": -107.42555,
  "elev": 14004,
  "range": "San Juan Mountains",
  "rank": 53,
  "route": "Sunshine Peak - Via Redcloud Peak",
  "cls": "Class 2",
  "dist": "12.25 mi",
  "gain": "4,800'",
  "exposure": "Moderate",
  "rockfall": "Moderate",
  "routefinding": "Low",
  "commitment": "Considerable"
 }
];

// Lake trails: not 14ers, shown as a separate always-visible category with
// their own map icon rather than folded into the peak/hub/difficulty system.
const LAKES = [
 {
  "name": "Hessie Trail (Lost Lake)",
  "hub": "georgetown",
  "lat": 39.95,
  "lon": -105.6147,
  "elev": 9850,
  "dist": "4.2 mi",
  "gain": "833'",
  "note": "Popular short hike west of Nederland from the Hessie Trailhead. Can hold snow well into summer."
 },
 {
  "name": "Lake Isabelle Trail",
  "hub": "estes-park",
  "lat": 40.0754,
  "lon": -105.651,
  "elev": 10872,
  "dist": "4.4 mi",
  "gain": "600'",
  "note": "From the Long Lake Trailhead in Brainard Lake Recreation Area, past Long Lake to a glacial lake beneath the Continental Divide."
 },
 {
  "name": "Dream Lake",
  "hub": "estes-park",
  "lat": 40.30944,
  "lon": -105.65889,
  "elev": 9905,
  "dist": "2.2 mi",
  "gain": "425'",
  "note": "From the Bear Lake Trailhead in Rocky Mountain National Park, past Nymph Lake. One of the park's most popular short hikes."
 },
 {
  "name": "Emerald Lake",
  "hub": "estes-park",
  "lat": 40.30923,
  "lon": -105.66146,
  "elev": 10110,
  "dist": "3.6 mi",
  "gain": "605'",
  "note": "Continues past Dream Lake from the same Bear Lake Trailhead to the highest of the three lakes on this trail."
 }
];
